# Example  .gitlab-ci.yml file
stages:
  - maventest
  - mavenbuild
  - androidtest
  - androidbuild


maven-build:   #this is a JOB
  stage: mavenbuild
  tags:
    - springboot_tag  # this is LINK to the shell runner on the remote-server 
  script:
    - cd Backend
    - mvn package -B

maven-test:
  stage: maventest
  tags:
    - springboot_tag
  script:
    - cd Backend
    - mvn test
  artifacts:
    paths:
      - Backend/target/*.jar

    

android-build:
  image: javiersantos/android-ci:latest
  stage: androidbuild
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/gradlew
  tags:
   - android_tag
  script:
    - cd Frontend
    - ./gradlew build
  artifacts:
    paths:
    - Android_test/app/build/outputs/

android-test:
  image: javiersantos/android-ci:latest
  stage: androidtest
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/gradlew
  tags:
   - android_tag
  script:
    - cd Frontend
    - ./gradlew test


